repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff-check
        args: [ --fix ]
        files: ^(src|scripts|tests)/.*\.(py|ipynb)$

      - id: ruff-check
        name: Sort imports
        args: [ --select, I, --fix ]
        files: ^(src|scripts|tests)/.*\.(py|ipynb)$
      
      - id: ruff-format
        files: ^(src|scripts|tests)/.*\.(py|ipynb)$