site_name: Felice models
theme:
  name: material
  logo: img/felice.png
  favicon: img/felice.png
  palette:
    primary: teal
  features:
    - navigation.path
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.code.annotate
copyright: >
  Felice models Â© 2026 by University of Groningen (Fernando M. Quintana) | 
  Code is licensed under <a href="https://opensource.org/licenses/MIT">MIT License</a> | Docs is licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">

nav:
  - Home: index.md
  - Neuron Models: 
    - neuron_models/index.md
    - WereRabbit:
      - neuron_models/wererabbit/index.md
      - Basic example: neuron_models/wererabbit/wererabbit.ipynb
    - FitzHugh-Nagumo:
      - neuron_models/fhn/index.md
      - Example: neuron_models/fhn/fhn.ipynb
    - Snowball:
      - Description: neuron_models/snowball/index.md
    - LIF:
      - Description: neuron_models/lif/index.md
  - API Reference:
    - api/index.md
    - Neuron Models: api/neuron_models.md
    - Solver: api/solver.md
    - Datasets: api/datasets.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_object_full_path: false
            show_category_heading: true
            show_symbol_type_heading: true
            members_order: source
            group_by_category: true
            show_signature_annotations: true
            separate_signature: false

  - mkdocs-jupyter
  - print-site